apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datascience-projects1
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - user: user1
        url: https://kubernetes.default.svc
      - user: user2
        url: https://kubernetes.default.svc      
  template:
    metadata:
      name: '{{.user}}-datascience-project'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/tsailiming/openshift-ai-gitops.git
        targetRevision: HEAD
        path: kustomize/overlays/{{.user}}
      destination:
        server: '{{.url}}'
        namespace: '{{.user}}-datascience-project'
      ignoreDifferences:
          - group: kubeflow.org
            kind: Notebook
            jsonPointers:
              - /metadata/generation
              - /spec/template/spec/containers/1
      syncOptions:
        - CreateNamespace=true