apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patches:
- target:
    kind: Namespace
    name: datascience-project
  patch: |-
    - op: replace
      path: /metadata/name
      value: user1-datascience-project
    - op: replace
      path: /metadata/annotations/openshift.io~1display-name
      value: user1-datascience-project
- target:
    kind: RoleBinding
    name: admin
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: user1