kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-pipeline-storage
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Pipeline Storage  
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_ENDPOINT_URL_S3: aHR0cHM6Ly9taW5pby11c2VyMS1kYXRhc2NpZW5jZS1wcm9qZWN0LmFwcHMuaXA5ajYuc2FuZGJveDMyMy5vcGVudGxjLmNvbQ==
  AWS_S3_BUCKET: cGlwZWxpbmUtc3RvcmFnZQ==
  AWS_S3_ENDPOINT: aHR0cHM6Ly9taW5pby11c2VyMS1kYXRhc2NpZW5jZS1wcm9qZWN0LmFwcHMuaXA5ajYuc2FuZGJveDMyMy5vcGVudGxjLmNvbQ==
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
type: Opaque