kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin  
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: PLACEHOLDER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
